<?php
/**
 * @author CreeperFace
 */

namespace synapsepm\network;


use pocketmine\network\mcpe\PlayerNetworkSessionAdapter;
use pocketmine\network\mcpe\protocol\SetLocalPlayerAsInitializedPacket;
use pocketmine\Server;

class SynapsePlayerNetworkSessionAdapter extends PlayerNetworkSessionAdapter {
    //TODO: may be useful in the future

    public function handleSetLocalPlayerAsInitialized(SetLocalPlayerAsInitializedPacket $packet): bool
    {
        // $this->player private... WTF PMMP!!!!!! Big facepalm
        foreach (Server::getInstance()->getOnlinePlayers() as $player) {
            if ($player->getId() == $packet->entityRuntimeId) {
                $player->setImmobile(false);
            }
        }
        return parent::handleSetLocalPlayerAsInitialized($packet); // TODO: Change the autogenerated stub
    }
}